name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-plugin:
    name: Build Plugin Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construire avec Gradle
        run: ./plugin/gradlew -p plugin clean build

      - name: Publier le JAR comme artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: plugin/build/libs/*.jar

  lint-datapack:
    name: Lint Datapack JSON
    runs-on: ubuntu-latest
    needs: build-plugin

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js (pour linter JSON)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer datapack-json-linter
        run: npm install -g datapack-json-linter

      - name: Lancer le linter
        run: |
          datapack-json-linter datapack/data/rpgplus

  package-datapack:
    name: Package Datapack & Resource-pack
    runs-on: ubuntu-latest
    needs: lint-datapack

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Zipper le datapack
        run: |
          cd datapack
          zip -r ../rpgplus-datapack.zip .

      - name: Zipper le resource-pack
        run: |
          cd resource-pack
          zip -r ../rpgplus-resource-pack.zip .

      - name: Publier les ZIPs comme artifacts
        uses: actions/upload-artifact@v3
        with:
          name: datapack-and-resources
          path: |
            rpgplus-datapack.zip
            rpgplus-resource-pack.zip
